#ifndef GHOST_INTERNAL_NETWORK_SERVERCOREGRPC_HPP
#define GHOST_INTERNAL_NETWORK_SERVERCOREGRPC_HPP

namespace ghost
{
	namespace internal
	{

	}
}

#endif // GHOST_INTERNAL_NETWORK_SERVERCOREGRPC_HPP
