// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ghost.proto

#include "Ghost.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_Ghost_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_Ghost_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ConnectionConfigurationField;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_Ghost_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_GenericMessageHeader;
}  // namespace protobuf_Ghost_2eproto
namespace ghost {
namespace internal {
namespace protobuf {
class GenericMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GenericMessage>
      _instance;
} _GenericMessage_default_instance_;
class GenericMessageHeaderDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GenericMessageHeader>
      _instance;
} _GenericMessageHeader_default_instance_;
class ConnectionConfigurationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ConnectionConfiguration>
      _instance;
} _ConnectionConfiguration_default_instance_;
class ConnectionConfigurationFieldDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ConnectionConfigurationField>
      _instance;
} _ConnectionConfigurationField_default_instance_;
}  // namespace protobuf
}  // namespace internal
}  // namespace ghost
namespace protobuf_Ghost_2eproto {
static void InitDefaultsGenericMessage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ghost::internal::protobuf::_GenericMessage_default_instance_;
    new (ptr) ::ghost::internal::protobuf::GenericMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ghost::internal::protobuf::GenericMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_GenericMessage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsGenericMessage}, {
      &protobuf_Ghost_2eproto::scc_info_GenericMessageHeader.base,}};

static void InitDefaultsGenericMessageHeader() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ghost::internal::protobuf::_GenericMessageHeader_default_instance_;
    new (ptr) ::ghost::internal::protobuf::GenericMessageHeader();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ghost::internal::protobuf::GenericMessageHeader::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GenericMessageHeader =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGenericMessageHeader}, {}};

static void InitDefaultsConnectionConfiguration() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ghost::internal::protobuf::_ConnectionConfiguration_default_instance_;
    new (ptr) ::ghost::internal::protobuf::ConnectionConfiguration();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ghost::internal::protobuf::ConnectionConfiguration::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ConnectionConfiguration =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsConnectionConfiguration}, {
      &protobuf_Ghost_2eproto::scc_info_ConnectionConfigurationField.base,}};

static void InitDefaultsConnectionConfigurationField() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ghost::internal::protobuf::_ConnectionConfigurationField_default_instance_;
    new (ptr) ::ghost::internal::protobuf::ConnectionConfigurationField();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ghost::internal::protobuf::ConnectionConfigurationField::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ConnectionConfigurationField =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsConnectionConfigurationField}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_GenericMessage.base);
  ::google::protobuf::internal::InitSCC(&scc_info_GenericMessageHeader.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ConnectionConfiguration.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ConnectionConfigurationField.base);
}

::google::protobuf::Metadata file_level_metadata[4];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::internal::protobuf::GenericMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::internal::protobuf::GenericMessage, header_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::internal::protobuf::GenericMessage, serial_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::internal::protobuf::GenericMessage, format_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::internal::protobuf::GenericMessage, name_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::internal::protobuf::GenericMessageHeader, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::internal::protobuf::GenericMessageHeader, timestamp_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::internal::protobuf::GenericMessageHeader, hostname_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::internal::protobuf::ConnectionConfiguration, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::internal::protobuf::ConnectionConfiguration, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::internal::protobuf::ConnectionConfiguration, fields_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::internal::protobuf::ConnectionConfigurationField, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::internal::protobuf::ConnectionConfigurationField, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::internal::protobuf::ConnectionConfigurationField, value_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ghost::internal::protobuf::GenericMessage)},
  { 9, -1, sizeof(::ghost::internal::protobuf::GenericMessageHeader)},
  { 16, -1, sizeof(::ghost::internal::protobuf::ConnectionConfiguration)},
  { 23, -1, sizeof(::ghost::internal::protobuf::ConnectionConfigurationField)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ghost::internal::protobuf::_GenericMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ghost::internal::protobuf::_GenericMessageHeader_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ghost::internal::protobuf::_ConnectionConfiguration_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ghost::internal::protobuf::_ConnectionConfigurationField_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "Ghost.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 4);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\013Ghost.proto\022\027ghost.internal.protobuf\032\031"
      "google/protobuf/any.proto\"}\n\016GenericMess"
      "age\022=\n\006header\030\001 \001(\0132-.ghost.internal.pro"
      "tobuf.GenericMessageHeader\022\016\n\006serial\030\002 \001"
      "(\t\022\016\n\006format\030\003 \001(\t\022\014\n\004name\030\004 \001(\t\";\n\024Gene"
      "ricMessageHeader\022\021\n\ttimestamp\030\001 \001(\003\022\020\n\010h"
      "ostname\030\002 \001(\t\"n\n\027ConnectionConfiguration"
      "\022\014\n\004name\030\001 \001(\t\022E\n\006fields\030\002 \003(\01325.ghost.i"
      "nternal.protobuf.ConnectionConfiguration"
      "Field\";\n\034ConnectionConfigurationField\022\014\n"
      "\004name\030\001 \001(\t\022\r\n\005value\030\002 \001(\t2R\n\023ServerClie"
      "ntService\022;\n\007connect\022\024.google.protobuf.A"
      "ny\032\024.google.protobuf.Any\"\000(\0010\001B\002P\001b\006prot"
      "o3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 522);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Ghost.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2fany_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_Ghost_2eproto
namespace ghost {
namespace internal {
namespace protobuf {

// ===================================================================

void GenericMessage::InitAsDefaultInstance() {
  ::ghost::internal::protobuf::_GenericMessage_default_instance_._instance.get_mutable()->header_ = const_cast< ::ghost::internal::protobuf::GenericMessageHeader*>(
      ::ghost::internal::protobuf::GenericMessageHeader::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GenericMessage::kHeaderFieldNumber;
const int GenericMessage::kSerialFieldNumber;
const int GenericMessage::kFormatFieldNumber;
const int GenericMessage::kNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GenericMessage::GenericMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_Ghost_2eproto::scc_info_GenericMessage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ghost.internal.protobuf.GenericMessage)
}
GenericMessage::GenericMessage(const GenericMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  serial_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.serial().size() > 0) {
    serial_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.serial_);
  }
  format_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.format().size() > 0) {
    format_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.format_);
  }
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.has_header()) {
    header_ = new ::ghost::internal::protobuf::GenericMessageHeader(*from.header_);
  } else {
    header_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:ghost.internal.protobuf.GenericMessage)
}

void GenericMessage::SharedCtor() {
  serial_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  format_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  header_ = NULL;
}

GenericMessage::~GenericMessage() {
  // @@protoc_insertion_point(destructor:ghost.internal.protobuf.GenericMessage)
  SharedDtor();
}

void GenericMessage::SharedDtor() {
  serial_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  format_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete header_;
}

void GenericMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GenericMessage::descriptor() {
  ::protobuf_Ghost_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Ghost_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GenericMessage& GenericMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_Ghost_2eproto::scc_info_GenericMessage.base);
  return *internal_default_instance();
}


void GenericMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:ghost.internal.protobuf.GenericMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  serial_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  format_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && header_ != NULL) {
    delete header_;
  }
  header_ = NULL;
  _internal_metadata_.Clear();
}

bool GenericMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ghost.internal.protobuf.GenericMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .ghost.internal.protobuf.GenericMessageHeader header = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string serial = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_serial()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->serial().data(), static_cast<int>(this->serial().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ghost.internal.protobuf.GenericMessage.serial"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string format = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_format()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->format().data(), static_cast<int>(this->format().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ghost.internal.protobuf.GenericMessage.format"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string name = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ghost.internal.protobuf.GenericMessage.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ghost.internal.protobuf.GenericMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ghost.internal.protobuf.GenericMessage)
  return false;
#undef DO_
}

void GenericMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ghost.internal.protobuf.GenericMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .ghost.internal.protobuf.GenericMessageHeader header = 1;
  if (this->has_header()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_header(), output);
  }

  // string serial = 2;
  if (this->serial().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->serial().data(), static_cast<int>(this->serial().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.internal.protobuf.GenericMessage.serial");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->serial(), output);
  }

  // string format = 3;
  if (this->format().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->format().data(), static_cast<int>(this->format().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.internal.protobuf.GenericMessage.format");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->format(), output);
  }

  // string name = 4;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.internal.protobuf.GenericMessage.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->name(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ghost.internal.protobuf.GenericMessage)
}

::google::protobuf::uint8* GenericMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ghost.internal.protobuf.GenericMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .ghost.internal.protobuf.GenericMessageHeader header = 1;
  if (this->has_header()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_header(), deterministic, target);
  }

  // string serial = 2;
  if (this->serial().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->serial().data(), static_cast<int>(this->serial().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.internal.protobuf.GenericMessage.serial");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->serial(), target);
  }

  // string format = 3;
  if (this->format().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->format().data(), static_cast<int>(this->format().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.internal.protobuf.GenericMessage.format");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->format(), target);
  }

  // string name = 4;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.internal.protobuf.GenericMessage.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->name(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ghost.internal.protobuf.GenericMessage)
  return target;
}

size_t GenericMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ghost.internal.protobuf.GenericMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string serial = 2;
  if (this->serial().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->serial());
  }

  // string format = 3;
  if (this->format().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->format());
  }

  // string name = 4;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // .ghost.internal.protobuf.GenericMessageHeader header = 1;
  if (this->has_header()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *header_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GenericMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ghost.internal.protobuf.GenericMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const GenericMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GenericMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ghost.internal.protobuf.GenericMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ghost.internal.protobuf.GenericMessage)
    MergeFrom(*source);
  }
}

void GenericMessage::MergeFrom(const GenericMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ghost.internal.protobuf.GenericMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.serial().size() > 0) {

    serial_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.serial_);
  }
  if (from.format().size() > 0) {

    format_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.format_);
  }
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.has_header()) {
    mutable_header()->::ghost::internal::protobuf::GenericMessageHeader::MergeFrom(from.header());
  }
}

void GenericMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ghost.internal.protobuf.GenericMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GenericMessage::CopyFrom(const GenericMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ghost.internal.protobuf.GenericMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GenericMessage::IsInitialized() const {
  return true;
}

void GenericMessage::Swap(GenericMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GenericMessage::InternalSwap(GenericMessage* other) {
  using std::swap;
  serial_.Swap(&other->serial_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  format_.Swap(&other->format_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(header_, other->header_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GenericMessage::GetMetadata() const {
  protobuf_Ghost_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Ghost_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GenericMessageHeader::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GenericMessageHeader::kTimestampFieldNumber;
const int GenericMessageHeader::kHostnameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GenericMessageHeader::GenericMessageHeader()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_Ghost_2eproto::scc_info_GenericMessageHeader.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ghost.internal.protobuf.GenericMessageHeader)
}
GenericMessageHeader::GenericMessageHeader(const GenericMessageHeader& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  hostname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.hostname().size() > 0) {
    hostname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hostname_);
  }
  timestamp_ = from.timestamp_;
  // @@protoc_insertion_point(copy_constructor:ghost.internal.protobuf.GenericMessageHeader)
}

void GenericMessageHeader::SharedCtor() {
  hostname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  timestamp_ = GOOGLE_LONGLONG(0);
}

GenericMessageHeader::~GenericMessageHeader() {
  // @@protoc_insertion_point(destructor:ghost.internal.protobuf.GenericMessageHeader)
  SharedDtor();
}

void GenericMessageHeader::SharedDtor() {
  hostname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void GenericMessageHeader::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GenericMessageHeader::descriptor() {
  ::protobuf_Ghost_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Ghost_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GenericMessageHeader& GenericMessageHeader::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_Ghost_2eproto::scc_info_GenericMessageHeader.base);
  return *internal_default_instance();
}


void GenericMessageHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:ghost.internal.protobuf.GenericMessageHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  hostname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  timestamp_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool GenericMessageHeader::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ghost.internal.protobuf.GenericMessageHeader)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 timestamp = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &timestamp_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string hostname = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_hostname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->hostname().data(), static_cast<int>(this->hostname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ghost.internal.protobuf.GenericMessageHeader.hostname"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ghost.internal.protobuf.GenericMessageHeader)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ghost.internal.protobuf.GenericMessageHeader)
  return false;
#undef DO_
}

void GenericMessageHeader::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ghost.internal.protobuf.GenericMessageHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 timestamp = 1;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->timestamp(), output);
  }

  // string hostname = 2;
  if (this->hostname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hostname().data(), static_cast<int>(this->hostname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.internal.protobuf.GenericMessageHeader.hostname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->hostname(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ghost.internal.protobuf.GenericMessageHeader)
}

::google::protobuf::uint8* GenericMessageHeader::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ghost.internal.protobuf.GenericMessageHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 timestamp = 1;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(1, this->timestamp(), target);
  }

  // string hostname = 2;
  if (this->hostname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hostname().data(), static_cast<int>(this->hostname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.internal.protobuf.GenericMessageHeader.hostname");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->hostname(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ghost.internal.protobuf.GenericMessageHeader)
  return target;
}

size_t GenericMessageHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ghost.internal.protobuf.GenericMessageHeader)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string hostname = 2;
  if (this->hostname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->hostname());
  }

  // int64 timestamp = 1;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->timestamp());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GenericMessageHeader::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ghost.internal.protobuf.GenericMessageHeader)
  GOOGLE_DCHECK_NE(&from, this);
  const GenericMessageHeader* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GenericMessageHeader>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ghost.internal.protobuf.GenericMessageHeader)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ghost.internal.protobuf.GenericMessageHeader)
    MergeFrom(*source);
  }
}

void GenericMessageHeader::MergeFrom(const GenericMessageHeader& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ghost.internal.protobuf.GenericMessageHeader)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.hostname().size() > 0) {

    hostname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hostname_);
  }
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
}

void GenericMessageHeader::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ghost.internal.protobuf.GenericMessageHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GenericMessageHeader::CopyFrom(const GenericMessageHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ghost.internal.protobuf.GenericMessageHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GenericMessageHeader::IsInitialized() const {
  return true;
}

void GenericMessageHeader::Swap(GenericMessageHeader* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GenericMessageHeader::InternalSwap(GenericMessageHeader* other) {
  using std::swap;
  hostname_.Swap(&other->hostname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(timestamp_, other->timestamp_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GenericMessageHeader::GetMetadata() const {
  protobuf_Ghost_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Ghost_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ConnectionConfiguration::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ConnectionConfiguration::kNameFieldNumber;
const int ConnectionConfiguration::kFieldsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ConnectionConfiguration::ConnectionConfiguration()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_Ghost_2eproto::scc_info_ConnectionConfiguration.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ghost.internal.protobuf.ConnectionConfiguration)
}
ConnectionConfiguration::ConnectionConfiguration(const ConnectionConfiguration& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      fields_(from.fields_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  // @@protoc_insertion_point(copy_constructor:ghost.internal.protobuf.ConnectionConfiguration)
}

void ConnectionConfiguration::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ConnectionConfiguration::~ConnectionConfiguration() {
  // @@protoc_insertion_point(destructor:ghost.internal.protobuf.ConnectionConfiguration)
  SharedDtor();
}

void ConnectionConfiguration::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ConnectionConfiguration::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ConnectionConfiguration::descriptor() {
  ::protobuf_Ghost_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Ghost_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ConnectionConfiguration& ConnectionConfiguration::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_Ghost_2eproto::scc_info_ConnectionConfiguration.base);
  return *internal_default_instance();
}


void ConnectionConfiguration::Clear() {
// @@protoc_insertion_point(message_clear_start:ghost.internal.protobuf.ConnectionConfiguration)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  fields_.Clear();
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ConnectionConfiguration::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ghost.internal.protobuf.ConnectionConfiguration)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ghost.internal.protobuf.ConnectionConfiguration.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .ghost.internal.protobuf.ConnectionConfigurationField fields = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_fields()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ghost.internal.protobuf.ConnectionConfiguration)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ghost.internal.protobuf.ConnectionConfiguration)
  return false;
#undef DO_
}

void ConnectionConfiguration::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ghost.internal.protobuf.ConnectionConfiguration)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.internal.protobuf.ConnectionConfiguration.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // repeated .ghost.internal.protobuf.ConnectionConfigurationField fields = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->fields_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->fields(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ghost.internal.protobuf.ConnectionConfiguration)
}

::google::protobuf::uint8* ConnectionConfiguration::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ghost.internal.protobuf.ConnectionConfiguration)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.internal.protobuf.ConnectionConfiguration.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // repeated .ghost.internal.protobuf.ConnectionConfigurationField fields = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->fields_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->fields(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ghost.internal.protobuf.ConnectionConfiguration)
  return target;
}

size_t ConnectionConfiguration::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ghost.internal.protobuf.ConnectionConfiguration)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .ghost.internal.protobuf.ConnectionConfigurationField fields = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->fields_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->fields(static_cast<int>(i)));
    }
  }

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConnectionConfiguration::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ghost.internal.protobuf.ConnectionConfiguration)
  GOOGLE_DCHECK_NE(&from, this);
  const ConnectionConfiguration* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ConnectionConfiguration>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ghost.internal.protobuf.ConnectionConfiguration)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ghost.internal.protobuf.ConnectionConfiguration)
    MergeFrom(*source);
  }
}

void ConnectionConfiguration::MergeFrom(const ConnectionConfiguration& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ghost.internal.protobuf.ConnectionConfiguration)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  fields_.MergeFrom(from.fields_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
}

void ConnectionConfiguration::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ghost.internal.protobuf.ConnectionConfiguration)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConnectionConfiguration::CopyFrom(const ConnectionConfiguration& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ghost.internal.protobuf.ConnectionConfiguration)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConnectionConfiguration::IsInitialized() const {
  return true;
}

void ConnectionConfiguration::Swap(ConnectionConfiguration* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ConnectionConfiguration::InternalSwap(ConnectionConfiguration* other) {
  using std::swap;
  CastToBase(&fields_)->InternalSwap(CastToBase(&other->fields_));
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ConnectionConfiguration::GetMetadata() const {
  protobuf_Ghost_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Ghost_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ConnectionConfigurationField::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ConnectionConfigurationField::kNameFieldNumber;
const int ConnectionConfigurationField::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ConnectionConfigurationField::ConnectionConfigurationField()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_Ghost_2eproto::scc_info_ConnectionConfigurationField.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ghost.internal.protobuf.ConnectionConfigurationField)
}
ConnectionConfigurationField::ConnectionConfigurationField(const ConnectionConfigurationField& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value().size() > 0) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  // @@protoc_insertion_point(copy_constructor:ghost.internal.protobuf.ConnectionConfigurationField)
}

void ConnectionConfigurationField::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ConnectionConfigurationField::~ConnectionConfigurationField() {
  // @@protoc_insertion_point(destructor:ghost.internal.protobuf.ConnectionConfigurationField)
  SharedDtor();
}

void ConnectionConfigurationField::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ConnectionConfigurationField::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ConnectionConfigurationField::descriptor() {
  ::protobuf_Ghost_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Ghost_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ConnectionConfigurationField& ConnectionConfigurationField::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_Ghost_2eproto::scc_info_ConnectionConfigurationField.base);
  return *internal_default_instance();
}


void ConnectionConfigurationField::Clear() {
// @@protoc_insertion_point(message_clear_start:ghost.internal.protobuf.ConnectionConfigurationField)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ConnectionConfigurationField::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ghost.internal.protobuf.ConnectionConfigurationField)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ghost.internal.protobuf.ConnectionConfigurationField.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value().data(), static_cast<int>(this->value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ghost.internal.protobuf.ConnectionConfigurationField.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ghost.internal.protobuf.ConnectionConfigurationField)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ghost.internal.protobuf.ConnectionConfigurationField)
  return false;
#undef DO_
}

void ConnectionConfigurationField::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ghost.internal.protobuf.ConnectionConfigurationField)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.internal.protobuf.ConnectionConfigurationField.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), static_cast<int>(this->value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.internal.protobuf.ConnectionConfigurationField.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ghost.internal.protobuf.ConnectionConfigurationField)
}

::google::protobuf::uint8* ConnectionConfigurationField::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ghost.internal.protobuf.ConnectionConfigurationField)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.internal.protobuf.ConnectionConfigurationField.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), static_cast<int>(this->value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.internal.protobuf.ConnectionConfigurationField.value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ghost.internal.protobuf.ConnectionConfigurationField)
  return target;
}

size_t ConnectionConfigurationField::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ghost.internal.protobuf.ConnectionConfigurationField)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string value = 2;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConnectionConfigurationField::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ghost.internal.protobuf.ConnectionConfigurationField)
  GOOGLE_DCHECK_NE(&from, this);
  const ConnectionConfigurationField* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ConnectionConfigurationField>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ghost.internal.protobuf.ConnectionConfigurationField)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ghost.internal.protobuf.ConnectionConfigurationField)
    MergeFrom(*source);
  }
}

void ConnectionConfigurationField::MergeFrom(const ConnectionConfigurationField& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ghost.internal.protobuf.ConnectionConfigurationField)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
}

void ConnectionConfigurationField::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ghost.internal.protobuf.ConnectionConfigurationField)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConnectionConfigurationField::CopyFrom(const ConnectionConfigurationField& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ghost.internal.protobuf.ConnectionConfigurationField)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConnectionConfigurationField::IsInitialized() const {
  return true;
}

void ConnectionConfigurationField::Swap(ConnectionConfigurationField* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ConnectionConfigurationField::InternalSwap(ConnectionConfigurationField* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  value_.Swap(&other->value_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ConnectionConfigurationField::GetMetadata() const {
  protobuf_Ghost_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_Ghost_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
}  // namespace internal
}  // namespace ghost
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ghost::internal::protobuf::GenericMessage* Arena::CreateMaybeMessage< ::ghost::internal::protobuf::GenericMessage >(Arena* arena) {
  return Arena::CreateInternal< ::ghost::internal::protobuf::GenericMessage >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ghost::internal::protobuf::GenericMessageHeader* Arena::CreateMaybeMessage< ::ghost::internal::protobuf::GenericMessageHeader >(Arena* arena) {
  return Arena::CreateInternal< ::ghost::internal::protobuf::GenericMessageHeader >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ghost::internal::protobuf::ConnectionConfiguration* Arena::CreateMaybeMessage< ::ghost::internal::protobuf::ConnectionConfiguration >(Arena* arena) {
  return Arena::CreateInternal< ::ghost::internal::protobuf::ConnectionConfiguration >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ghost::internal::protobuf::ConnectionConfigurationField* Arena::CreateMaybeMessage< ::ghost::internal::protobuf::ConnectionConfigurationField >(Arena* arena) {
  return Arena::CreateInternal< ::ghost::internal::protobuf::ConnectionConfigurationField >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
