// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ghost/connection/ConnectionConfiguration.proto

#include "ghost/connection/ConnectionConfiguration.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ConnectionConfigurationField;
}  // namespace protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto
namespace ghost {
namespace protobuf {
namespace connection {
class ConnectionConfigurationDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ConnectionConfiguration>
      _instance;
} _ConnectionConfiguration_default_instance_;
class ConnectionConfigurationFieldDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ConnectionConfigurationField>
      _instance;
} _ConnectionConfigurationField_default_instance_;
}  // namespace connection
}  // namespace protobuf
}  // namespace ghost
namespace protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto {
static void InitDefaultsConnectionConfiguration() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ghost::protobuf::connection::_ConnectionConfiguration_default_instance_;
    new (ptr) ::ghost::protobuf::connection::ConnectionConfiguration();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ghost::protobuf::connection::ConnectionConfiguration::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ConnectionConfiguration =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsConnectionConfiguration}, {
      &protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto::scc_info_ConnectionConfigurationField.base,}};

static void InitDefaultsConnectionConfigurationField() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ghost::protobuf::connection::_ConnectionConfigurationField_default_instance_;
    new (ptr) ::ghost::protobuf::connection::ConnectionConfigurationField();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ghost::protobuf::connection::ConnectionConfigurationField::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ConnectionConfigurationField =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsConnectionConfigurationField}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ConnectionConfiguration.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ConnectionConfigurationField.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::protobuf::connection::ConnectionConfiguration, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::protobuf::connection::ConnectionConfiguration, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::protobuf::connection::ConnectionConfiguration, fields_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::protobuf::connection::ConnectionConfigurationField, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::protobuf::connection::ConnectionConfigurationField, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ghost::protobuf::connection::ConnectionConfigurationField, value_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ghost::protobuf::connection::ConnectionConfiguration)},
  { 7, -1, sizeof(::ghost::protobuf::connection::ConnectionConfigurationField)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ghost::protobuf::connection::_ConnectionConfiguration_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ghost::protobuf::connection::_ConnectionConfigurationField_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "ghost/connection/ConnectionConfiguration.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n.ghost/connection/ConnectionConfigurati"
      "on.proto\022\031ghost.protobuf.connection\032\031goo"
      "gle/protobuf/any.proto\"p\n\027ConnectionConf"
      "iguration\022\014\n\004name\030\001 \001(\t\022G\n\006fields\030\002 \003(\0132"
      "7.ghost.protobuf.connection.ConnectionCo"
      "nfigurationField\";\n\034ConnectionConfigurat"
      "ionField\022\014\n\004name\030\001 \001(\t\022\r\n\005value\030\002 \001(\tB\002P"
      "\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 289);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "ghost/connection/ConnectionConfiguration.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fprotobuf_2fany_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto
namespace ghost {
namespace protobuf {
namespace connection {

// ===================================================================

void ConnectionConfiguration::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ConnectionConfiguration::kNameFieldNumber;
const int ConnectionConfiguration::kFieldsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ConnectionConfiguration::ConnectionConfiguration()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto::scc_info_ConnectionConfiguration.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ghost.protobuf.connection.ConnectionConfiguration)
}
ConnectionConfiguration::ConnectionConfiguration(const ConnectionConfiguration& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      fields_(from.fields_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  // @@protoc_insertion_point(copy_constructor:ghost.protobuf.connection.ConnectionConfiguration)
}

void ConnectionConfiguration::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ConnectionConfiguration::~ConnectionConfiguration() {
  // @@protoc_insertion_point(destructor:ghost.protobuf.connection.ConnectionConfiguration)
  SharedDtor();
}

void ConnectionConfiguration::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ConnectionConfiguration::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ConnectionConfiguration::descriptor() {
  ::protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ConnectionConfiguration& ConnectionConfiguration::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto::scc_info_ConnectionConfiguration.base);
  return *internal_default_instance();
}


void ConnectionConfiguration::Clear() {
// @@protoc_insertion_point(message_clear_start:ghost.protobuf.connection.ConnectionConfiguration)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  fields_.Clear();
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ConnectionConfiguration::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ghost.protobuf.connection.ConnectionConfiguration)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ghost.protobuf.connection.ConnectionConfiguration.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .ghost.protobuf.connection.ConnectionConfigurationField fields = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_fields()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ghost.protobuf.connection.ConnectionConfiguration)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ghost.protobuf.connection.ConnectionConfiguration)
  return false;
#undef DO_
}

void ConnectionConfiguration::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ghost.protobuf.connection.ConnectionConfiguration)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.protobuf.connection.ConnectionConfiguration.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // repeated .ghost.protobuf.connection.ConnectionConfigurationField fields = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->fields_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->fields(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ghost.protobuf.connection.ConnectionConfiguration)
}

::google::protobuf::uint8* ConnectionConfiguration::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ghost.protobuf.connection.ConnectionConfiguration)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.protobuf.connection.ConnectionConfiguration.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // repeated .ghost.protobuf.connection.ConnectionConfigurationField fields = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->fields_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->fields(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ghost.protobuf.connection.ConnectionConfiguration)
  return target;
}

size_t ConnectionConfiguration::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ghost.protobuf.connection.ConnectionConfiguration)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .ghost.protobuf.connection.ConnectionConfigurationField fields = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->fields_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->fields(static_cast<int>(i)));
    }
  }

  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConnectionConfiguration::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ghost.protobuf.connection.ConnectionConfiguration)
  GOOGLE_DCHECK_NE(&from, this);
  const ConnectionConfiguration* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ConnectionConfiguration>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ghost.protobuf.connection.ConnectionConfiguration)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ghost.protobuf.connection.ConnectionConfiguration)
    MergeFrom(*source);
  }
}

void ConnectionConfiguration::MergeFrom(const ConnectionConfiguration& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ghost.protobuf.connection.ConnectionConfiguration)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  fields_.MergeFrom(from.fields_);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
}

void ConnectionConfiguration::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ghost.protobuf.connection.ConnectionConfiguration)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConnectionConfiguration::CopyFrom(const ConnectionConfiguration& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ghost.protobuf.connection.ConnectionConfiguration)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConnectionConfiguration::IsInitialized() const {
  return true;
}

void ConnectionConfiguration::Swap(ConnectionConfiguration* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ConnectionConfiguration::InternalSwap(ConnectionConfiguration* other) {
  using std::swap;
  CastToBase(&fields_)->InternalSwap(CastToBase(&other->fields_));
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ConnectionConfiguration::GetMetadata() const {
  protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ConnectionConfigurationField::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ConnectionConfigurationField::kNameFieldNumber;
const int ConnectionConfigurationField::kValueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ConnectionConfigurationField::ConnectionConfigurationField()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto::scc_info_ConnectionConfigurationField.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ghost.protobuf.connection.ConnectionConfigurationField)
}
ConnectionConfigurationField::ConnectionConfigurationField(const ConnectionConfigurationField& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.value().size() > 0) {
    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
  // @@protoc_insertion_point(copy_constructor:ghost.protobuf.connection.ConnectionConfigurationField)
}

void ConnectionConfigurationField::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ConnectionConfigurationField::~ConnectionConfigurationField() {
  // @@protoc_insertion_point(destructor:ghost.protobuf.connection.ConnectionConfigurationField)
  SharedDtor();
}

void ConnectionConfigurationField::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ConnectionConfigurationField::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ConnectionConfigurationField::descriptor() {
  ::protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ConnectionConfigurationField& ConnectionConfigurationField::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto::scc_info_ConnectionConfigurationField.base);
  return *internal_default_instance();
}


void ConnectionConfigurationField::Clear() {
// @@protoc_insertion_point(message_clear_start:ghost.protobuf.connection.ConnectionConfigurationField)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ConnectionConfigurationField::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ghost.protobuf.connection.ConnectionConfigurationField)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ghost.protobuf.connection.ConnectionConfigurationField.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string value = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_value()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->value().data(), static_cast<int>(this->value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ghost.protobuf.connection.ConnectionConfigurationField.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ghost.protobuf.connection.ConnectionConfigurationField)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ghost.protobuf.connection.ConnectionConfigurationField)
  return false;
#undef DO_
}

void ConnectionConfigurationField::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ghost.protobuf.connection.ConnectionConfigurationField)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.protobuf.connection.ConnectionConfigurationField.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), static_cast<int>(this->value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.protobuf.connection.ConnectionConfigurationField.value");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->value(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ghost.protobuf.connection.ConnectionConfigurationField)
}

::google::protobuf::uint8* ConnectionConfigurationField::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ghost.protobuf.connection.ConnectionConfigurationField)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.protobuf.connection.ConnectionConfigurationField.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // string value = 2;
  if (this->value().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->value().data(), static_cast<int>(this->value().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ghost.protobuf.connection.ConnectionConfigurationField.value");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->value(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ghost.protobuf.connection.ConnectionConfigurationField)
  return target;
}

size_t ConnectionConfigurationField::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ghost.protobuf.connection.ConnectionConfigurationField)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string value = 2;
  if (this->value().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ConnectionConfigurationField::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ghost.protobuf.connection.ConnectionConfigurationField)
  GOOGLE_DCHECK_NE(&from, this);
  const ConnectionConfigurationField* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ConnectionConfigurationField>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ghost.protobuf.connection.ConnectionConfigurationField)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ghost.protobuf.connection.ConnectionConfigurationField)
    MergeFrom(*source);
  }
}

void ConnectionConfigurationField::MergeFrom(const ConnectionConfigurationField& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ghost.protobuf.connection.ConnectionConfigurationField)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.value().size() > 0) {

    value_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.value_);
  }
}

void ConnectionConfigurationField::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ghost.protobuf.connection.ConnectionConfigurationField)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ConnectionConfigurationField::CopyFrom(const ConnectionConfigurationField& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ghost.protobuf.connection.ConnectionConfigurationField)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ConnectionConfigurationField::IsInitialized() const {
  return true;
}

void ConnectionConfigurationField::Swap(ConnectionConfigurationField* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ConnectionConfigurationField::InternalSwap(ConnectionConfigurationField* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  value_.Swap(&other->value_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ConnectionConfigurationField::GetMetadata() const {
  protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace connection
}  // namespace protobuf
}  // namespace ghost
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ghost::protobuf::connection::ConnectionConfiguration* Arena::CreateMaybeMessage< ::ghost::protobuf::connection::ConnectionConfiguration >(Arena* arena) {
  return Arena::CreateInternal< ::ghost::protobuf::connection::ConnectionConfiguration >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ghost::protobuf::connection::ConnectionConfigurationField* Arena::CreateMaybeMessage< ::ghost::protobuf::connection::ConnectionConfigurationField >(Arena* arena) {
  return Arena::CreateInternal< ::ghost::protobuf::connection::ConnectionConfigurationField >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
