// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ghost/connection/ConnectionConfiguration.proto

#ifndef PROTOBUF_INCLUDED_ghost_2fconnection_2fConnectionConfiguration_2eproto
#define PROTOBUF_INCLUDED_ghost_2fconnection_2fConnectionConfiguration_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include <google/protobuf/any.pb.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto 

namespace protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto
namespace ghost {
namespace protobuf {
namespace connection {
class ConnectionConfiguration;
class ConnectionConfigurationDefaultTypeInternal;
extern ConnectionConfigurationDefaultTypeInternal _ConnectionConfiguration_default_instance_;
class ConnectionConfigurationField;
class ConnectionConfigurationFieldDefaultTypeInternal;
extern ConnectionConfigurationFieldDefaultTypeInternal _ConnectionConfigurationField_default_instance_;
}  // namespace connection
}  // namespace protobuf
}  // namespace ghost
namespace google {
namespace protobuf {
template<> ::ghost::protobuf::connection::ConnectionConfiguration* Arena::CreateMaybeMessage<::ghost::protobuf::connection::ConnectionConfiguration>(Arena*);
template<> ::ghost::protobuf::connection::ConnectionConfigurationField* Arena::CreateMaybeMessage<::ghost::protobuf::connection::ConnectionConfigurationField>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace ghost {
namespace protobuf {
namespace connection {

// ===================================================================

class ConnectionConfiguration : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ghost.protobuf.connection.ConnectionConfiguration) */ {
 public:
  ConnectionConfiguration();
  virtual ~ConnectionConfiguration();

  ConnectionConfiguration(const ConnectionConfiguration& from);

  inline ConnectionConfiguration& operator=(const ConnectionConfiguration& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConnectionConfiguration(ConnectionConfiguration&& from) noexcept
    : ConnectionConfiguration() {
    *this = ::std::move(from);
  }

  inline ConnectionConfiguration& operator=(ConnectionConfiguration&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ConnectionConfiguration& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConnectionConfiguration* internal_default_instance() {
    return reinterpret_cast<const ConnectionConfiguration*>(
               &_ConnectionConfiguration_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ConnectionConfiguration* other);
  friend void swap(ConnectionConfiguration& a, ConnectionConfiguration& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConnectionConfiguration* New() const final {
    return CreateMaybeMessage<ConnectionConfiguration>(NULL);
  }

  ConnectionConfiguration* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ConnectionConfiguration>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ConnectionConfiguration& from);
  void MergeFrom(const ConnectionConfiguration& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConnectionConfiguration* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ghost.protobuf.connection.ConnectionConfigurationField fields = 2;
  int fields_size() const;
  void clear_fields();
  static const int kFieldsFieldNumber = 2;
  ::ghost::protobuf::connection::ConnectionConfigurationField* mutable_fields(int index);
  ::google::protobuf::RepeatedPtrField< ::ghost::protobuf::connection::ConnectionConfigurationField >*
      mutable_fields();
  const ::ghost::protobuf::connection::ConnectionConfigurationField& fields(int index) const;
  ::ghost::protobuf::connection::ConnectionConfigurationField* add_fields();
  const ::google::protobuf::RepeatedPtrField< ::ghost::protobuf::connection::ConnectionConfigurationField >&
      fields() const;

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:ghost.protobuf.connection.ConnectionConfiguration)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::ghost::protobuf::connection::ConnectionConfigurationField > fields_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ConnectionConfigurationField : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ghost.protobuf.connection.ConnectionConfigurationField) */ {
 public:
  ConnectionConfigurationField();
  virtual ~ConnectionConfigurationField();

  ConnectionConfigurationField(const ConnectionConfigurationField& from);

  inline ConnectionConfigurationField& operator=(const ConnectionConfigurationField& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ConnectionConfigurationField(ConnectionConfigurationField&& from) noexcept
    : ConnectionConfigurationField() {
    *this = ::std::move(from);
  }

  inline ConnectionConfigurationField& operator=(ConnectionConfigurationField&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ConnectionConfigurationField& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ConnectionConfigurationField* internal_default_instance() {
    return reinterpret_cast<const ConnectionConfigurationField*>(
               &_ConnectionConfigurationField_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ConnectionConfigurationField* other);
  friend void swap(ConnectionConfigurationField& a, ConnectionConfigurationField& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ConnectionConfigurationField* New() const final {
    return CreateMaybeMessage<ConnectionConfigurationField>(NULL);
  }

  ConnectionConfigurationField* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ConnectionConfigurationField>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ConnectionConfigurationField& from);
  void MergeFrom(const ConnectionConfigurationField& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ConnectionConfigurationField* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::std::string& value() const;
  void set_value(const ::std::string& value);
  #if LANG_CXX11
  void set_value(::std::string&& value);
  #endif
  void set_value(const char* value);
  void set_value(const char* value, size_t size);
  ::std::string* mutable_value();
  ::std::string* release_value();
  void set_allocated_value(::std::string* value);

  // @@protoc_insertion_point(class_scope:ghost.protobuf.connection.ConnectionConfigurationField)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ghost_2fconnection_2fConnectionConfiguration_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ConnectionConfiguration

// string name = 1;
inline void ConnectionConfiguration::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConnectionConfiguration::name() const {
  // @@protoc_insertion_point(field_get:ghost.protobuf.connection.ConnectionConfiguration.name)
  return name_.GetNoArena();
}
inline void ConnectionConfiguration::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ghost.protobuf.connection.ConnectionConfiguration.name)
}
#if LANG_CXX11
inline void ConnectionConfiguration::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ghost.protobuf.connection.ConnectionConfiguration.name)
}
#endif
inline void ConnectionConfiguration::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ghost.protobuf.connection.ConnectionConfiguration.name)
}
inline void ConnectionConfiguration::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ghost.protobuf.connection.ConnectionConfiguration.name)
}
inline ::std::string* ConnectionConfiguration::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:ghost.protobuf.connection.ConnectionConfiguration.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConnectionConfiguration::release_name() {
  // @@protoc_insertion_point(field_release:ghost.protobuf.connection.ConnectionConfiguration.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConnectionConfiguration::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:ghost.protobuf.connection.ConnectionConfiguration.name)
}

// repeated .ghost.protobuf.connection.ConnectionConfigurationField fields = 2;
inline int ConnectionConfiguration::fields_size() const {
  return fields_.size();
}
inline void ConnectionConfiguration::clear_fields() {
  fields_.Clear();
}
inline ::ghost::protobuf::connection::ConnectionConfigurationField* ConnectionConfiguration::mutable_fields(int index) {
  // @@protoc_insertion_point(field_mutable:ghost.protobuf.connection.ConnectionConfiguration.fields)
  return fields_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::ghost::protobuf::connection::ConnectionConfigurationField >*
ConnectionConfiguration::mutable_fields() {
  // @@protoc_insertion_point(field_mutable_list:ghost.protobuf.connection.ConnectionConfiguration.fields)
  return &fields_;
}
inline const ::ghost::protobuf::connection::ConnectionConfigurationField& ConnectionConfiguration::fields(int index) const {
  // @@protoc_insertion_point(field_get:ghost.protobuf.connection.ConnectionConfiguration.fields)
  return fields_.Get(index);
}
inline ::ghost::protobuf::connection::ConnectionConfigurationField* ConnectionConfiguration::add_fields() {
  // @@protoc_insertion_point(field_add:ghost.protobuf.connection.ConnectionConfiguration.fields)
  return fields_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ghost::protobuf::connection::ConnectionConfigurationField >&
ConnectionConfiguration::fields() const {
  // @@protoc_insertion_point(field_list:ghost.protobuf.connection.ConnectionConfiguration.fields)
  return fields_;
}

// -------------------------------------------------------------------

// ConnectionConfigurationField

// string name = 1;
inline void ConnectionConfigurationField::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConnectionConfigurationField::name() const {
  // @@protoc_insertion_point(field_get:ghost.protobuf.connection.ConnectionConfigurationField.name)
  return name_.GetNoArena();
}
inline void ConnectionConfigurationField::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ghost.protobuf.connection.ConnectionConfigurationField.name)
}
#if LANG_CXX11
inline void ConnectionConfigurationField::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ghost.protobuf.connection.ConnectionConfigurationField.name)
}
#endif
inline void ConnectionConfigurationField::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ghost.protobuf.connection.ConnectionConfigurationField.name)
}
inline void ConnectionConfigurationField::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ghost.protobuf.connection.ConnectionConfigurationField.name)
}
inline ::std::string* ConnectionConfigurationField::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:ghost.protobuf.connection.ConnectionConfigurationField.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConnectionConfigurationField::release_name() {
  // @@protoc_insertion_point(field_release:ghost.protobuf.connection.ConnectionConfigurationField.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConnectionConfigurationField::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:ghost.protobuf.connection.ConnectionConfigurationField.name)
}

// string value = 2;
inline void ConnectionConfigurationField::clear_value() {
  value_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ConnectionConfigurationField::value() const {
  // @@protoc_insertion_point(field_get:ghost.protobuf.connection.ConnectionConfigurationField.value)
  return value_.GetNoArena();
}
inline void ConnectionConfigurationField::set_value(const ::std::string& value) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:ghost.protobuf.connection.ConnectionConfigurationField.value)
}
#if LANG_CXX11
inline void ConnectionConfigurationField::set_value(::std::string&& value) {
  
  value_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:ghost.protobuf.connection.ConnectionConfigurationField.value)
}
#endif
inline void ConnectionConfigurationField::set_value(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:ghost.protobuf.connection.ConnectionConfigurationField.value)
}
inline void ConnectionConfigurationField::set_value(const char* value, size_t size) {
  
  value_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:ghost.protobuf.connection.ConnectionConfigurationField.value)
}
inline ::std::string* ConnectionConfigurationField::mutable_value() {
  
  // @@protoc_insertion_point(field_mutable:ghost.protobuf.connection.ConnectionConfigurationField.value)
  return value_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ConnectionConfigurationField::release_value() {
  // @@protoc_insertion_point(field_release:ghost.protobuf.connection.ConnectionConfigurationField.value)
  
  return value_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ConnectionConfigurationField::set_allocated_value(::std::string* value) {
  if (value != NULL) {
    
  } else {
    
  }
  value_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set_allocated:ghost.protobuf.connection.ConnectionConfigurationField.value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace connection
}  // namespace protobuf
}  // namespace ghost

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_ghost_2fconnection_2fConnectionConfiguration_2eproto
